# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(570, 340)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load = QtWidgets.QToolButton(Form)
        self.load.setObjectName("load")
        self.horizontalLayout.addWidget(self.load)
        self.save = QtWidgets.QToolButton(Form)
        self.save.setObjectName("save")
        self.horizontalLayout.addWidget(self.save)
        self.save_as = QtWidgets.QToolButton(Form)
        self.save_as.setObjectName("save_as")
        self.horizontalLayout.addWidget(self.save_as)
        self.expand_all = QtWidgets.QToolButton(Form)
        self.expand_all.setObjectName("expand_all")
        self.horizontalLayout.addWidget(self.expand_all)
        self.collapse_all = QtWidgets.QToolButton(Form)
        self.collapse_all.setObjectName("collapse_all")
        self.horizontalLayout.addWidget(self.collapse_all)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeView = QtWidgets.QTreeView(Form)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.load.setText(_translate("Form", "Load"))
        self.save.setText(_translate("Form", "Save"))
        self.save_as.setText(_translate("Form", "Save as"))
        self.expand_all.setText(_translate("Form", "Expand all"))
        self.collapse_all.setText(_translate("Form", "Collapse all"))
